stages:
  - build
  - push

build-flakes:
  stage: build
  image: nixos/nix:latest
  tags:
    - docker
  script:
    - ./pipelines/nix/nix-build.sh
    - tofu init
    - tofu apply -auto-approve
  artifacts:
    paths:
      - result-nonsym/
