stages:
  - build
  - push

build-flakes:
  stage: build
  image: nixos/nix:latest
  cache:
    key: "cache-$CI_COMMIT_REF_SLUG"
    fallback_keys:
      - "cache-$CI_DEFAULT_BRANCH"
      - "cache-default"
    paths:
      - /nix/store
      - /nix/var/nix/gcroots
  script:
    - ./pipelines/nix/nix-build.sh
  artifacts:
    paths:
      - result-nonsym/
