name: Build docker image
on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: nix-tofu:latest
